In [25]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [26]:
base = pd.read_csv('test.csv')

In [27]:
base.head()

,Amostra 1,Amostra 2,Amostra 3,Amostra 4,Amostra 5,Amostra 6,Amostra 7,Amostra 8,Amostra 9,Amostra 10,...,Amostra 93,Amostra 94,Amostra 95,Amostra 96,Amostra 97,Amostra 98,Amostra 99,Amostra 100,Amostra 101,Forma de onda
0,0.0,0.063,0.125,0.187,0.249,0.309,0.368,0.426,0.482,0.536,...,-0.482,-0.426,-0.368,-0.309,-0.249,-0.187,-0.125,-0.063,0.0,1.0
1,0.0,0.126,0.251,0.375,0.497,0.618,0.736,0.852,0.964,1.072,...,-0.964,-0.852,-0.736,-0.618,-0.497,-0.375,-0.251,-0.126,0.0,1.0
2,0.0,0.251,0.501,0.750,0.995,1.236,1.472,1.703,1.927,2.143,...,-1.927,-1.703,-1.472,-1.236,-0.995,-0.750,-0.501,-0.251,0.0,1.0
3,0.0,0.502,1.003,1.499,1.990,2.472,2.945,3.406,3.854,4.287,...,-3.854,-3.406,-2.945,-2.472,-1.990,-1.499,-1.003,-0.502,0.0,1.0
4,0.0,0.628,1.253,1.874,2.487,3.090,3.681,4.258,4.818,5.358,...,-4.818,-4.258,-3.681,-3.090,-2.487,-1.874,-1.253,-0.628,0.0,1.0

In [28]:
base.shape

(5, 102)

In [39]:
x = base.drop('Forma de onda', axis=1) # atributos previsores
x

,Amostra 1,Amostra 2,Amostra 3,Amostra 4,Amostra 5,Amostra 6,Amostra 7,Amostra 8,Amostra 9,Amostra 10,...,Amostra 92,Amostra 93,Amostra 94,Amostra 95,Amostra 96,Amostra 97,Amostra 98,Amostra 99,Amostra 100,Amostra 101
0,0.0,0.063,0.125,0.187,0.249,0.309,0.368,0.426,0.482,0.536,...,-0.536,-0.482,-0.426,-0.368,-0.309,-0.249,-0.187,-0.125,-0.063,0.0
1,0.0,0.126,0.251,0.375,0.497,0.618,0.736,0.852,0.964,1.072,...,-1.072,-0.964,-0.852,-0.736,-0.618,-0.497,-0.375,-0.251,-0.126,0.0
2,0.0,0.251,0.501,0.750,0.995,1.236,1.472,1.703,1.927,2.143,...,-2.143,-1.927,-1.703,-1.472,-1.236,-0.995,-0.750,-0.501,-0.251,0.0
3,0.0,0.502,1.003,1.499,1.990,2.472,2.945,3.406,3.854,4.287,...,-4.287,-3.854,-3.406,-2.945,-2.472,-1.990,-1.499,-1.003,-0.502,0.0
4,0.0,0.628,1.253,1.874,2.487,3.090,3.681,4.258,4.818,5.358,...,-5.358,-4.818,-4.258,-3.681,-3.090,-2.487,-1.874,-1.253,-0.628,0.0

In [38]:
y = base.iloc[:,-1] # pegando a ultima coluna para saber qual a classe
y

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: Forma de onda, dtype: float64